//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliviry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> DishID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
    
        public virtual Dishes Dishes { get; set; }
    }
}
